steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/beanhealth-backend:$COMMIT_SHA"
      - -f
      - backend/Dockerfile
      - backend

images:
  - "$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/beanhealth-backend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
